[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaCustom.ligations]
enables = ["kern-dotty", "kern-bars", "html-comment", "arrow-lr", "lteq-separate", "ltgt-diamond-tag", "slash-asterisk"]

[buildPlans.IosevkaCustom.metricOverride]
parenSize = 880

[buildPlans.IosevkaCustom.variants.design]
one = "base"
two = "curly-neck-serifless"
three = "two-arcs"
four = "closed-non-crossing-serifless"
five = "upright-arched-serifless"
six = "closed-contour"
seven = "straight-serifless"
eight = "two-circles"
nine = "closed-contour"
zero = "slashed"
capital-a = "curly-serifless"
capital-b = "standard-serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "curly-serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "horizontal-tailed"
capital-r = "standing-serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "curly-serifless"
capital-w = "straight-vertical-sides-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
e = "flat-crossbar"
f = "serifless"
g = "single-storey-earless-corner"
h = "straight-serifless"
i = "serifed"
j = "serifed"
k = "curly-serifless"
l = "zshaped"
m = "short-leg-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
s = "serifless"
t = "bent-hook-short-neck"
u = "toothless-corner-serifless"
v = "curly-serifless"
w = "straight-serifless"
x = "curly-serifless"
y = "curly-serifless"
z = "curly-serifless"
asterisk = "hex-mid"
underscore = "above-baseline"
paren = "normal"
brace = "curly"
guillemet = "straight"
ampersand = "closed"
at = "fourfold-solid-inner"
dollar = "open"
cent = "open"
percent = "rings-segmented-slash"
bar = "force-upright"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

[buildPlans.IosevkaCustom.variants.italic]
one = "base"
two = "curly-neck-serifless"
three = "two-arcs"
four = "closed-non-crossing-serifless"
five = "upright-arched-serifless"
six = "closed-contour"
seven = "straight-serifless"
eight = "two-circles"
nine = "closed-contour"
zero = "slashed"
capital-a = "curly-serifless"
capital-b = "standard-serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "curly-serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "horizontal-tailed"
capital-r = "standing-serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "curly-serifless"
capital-w = "straight-vertical-sides-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifless"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner-serifless"
c = "unilateral-inward-serifed"
d = "toothless-corner-serifless"
e = "rounded"
f = "flat-hook-serifless"
g = "double-storey"
h = "tailed-serifless"
i = "tailed-serifed"
j = "serifless"
k = "cursive-serifless"
l = "tailed-serifed"
m = "short-leg-tailed-serifless"
n = "earless-corner-tailed-serifless"
p = "earless-corner-serifless"
q = "earless-corner-diagonal-tailed-serifless"
r = "earless-corner-serifless"
s = "serifless"
t = "bent-hook-short-neck"
u = "tailed-serifless"
v = "curly-serifless"
w = "straight-serifless"
x = "semi-chancery-curly-serifless"
y = "cursive-flat-hook-serifless"
z = "cursive"
asterisk = "hex-mid"
underscore = "above-baseline"
paren = "normal"
brace = "curly"
guillemet = "straight"
ampersand = "closed"
at = "fourfold-solid-inner"
dollar = "open"
cent = "open"
percent = "rings-segmented-slash"
bar = "force-upright"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"
